---
- name: Install Python & pip
  apt:
    name:
      - python3
      - python3-pip
    state: present
  become: yes

- name: Copy Flask app
  copy:
    src: /home/terraform-user/app/   # your local app folder
    dest: /opt/myapp/
  become: yes

- name: Install dependencies
  pip:
    requirements: /opt/myapp/requirements.txt
    executable: pip3

- name: Deploy systemd service
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/myapp.service
  become: yes
  notify: Restart myapp
