---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  become: yes

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: true
  become: yes

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root

- name: Create DB user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_user: root

- name: Import schema
  mysql_db:
    name: "{{ db_name }}"
    state: import
    target: "{{ role_path }}/templates/schema.sql.j2"
    login_user: root
